# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate objc

Name:           rust-objc
Version:        0.2.0
Release:        %autorelease
Summary:        Objective-C Runtime bindings and wrapper for Rust

License:        MIT
URL:            https://crates.io/crates/objc
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Objective-C Runtime bindings and wrapper for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+exception-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+exception-devel %{_description}

This package contains library source intended for building other packages which
use the "exception" feature of the "%{crate}" crate.

%files       -n %{name}+exception-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+objc_exception-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+objc_exception-devel %{_description}

This package contains library source intended for building other packages which
use the "objc_exception" feature of the "%{crate}" crate.

%files       -n %{name}+objc_exception-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+verify_message-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+verify_message-devel %{_description}

This package contains library source intended for building other packages which
use the "verify_message" feature of the "%{crate}" crate.

%files       -n %{name}+verify_message-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
