# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate async-tungstenite

Name:           rust-async-tungstenite
Version:        0.16.0
Release:        %autorelease
Summary:        Async binding for Tungstenite, the Lightweight stream-based WebSocket implementation

License:        MIT
URL:            https://crates.io/crates/async-tungstenite
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Async binding for Tungstenite, the Lightweight stream-based WebSocket
implementation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "async-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+async-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "async-std" feature of the "%{crate}" crate.

%files       -n %{name}+async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-std-runtime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-std-runtime-devel %{_description}

This package contains library source intended for building other packages which
use the "async-std-runtime" feature of the "%{crate}" crate.

%files       -n %{name}+async-std-runtime-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "async-tls" feature of the "%{crate}" crate.

%files       -n %{name}+async-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gio-devel %{_description}

This package contains library source intended for building other packages which
use the "gio" feature of the "%{crate}" crate.

%files       -n %{name}+gio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+gio-runtime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+gio-runtime-devel %{_description}

This package contains library source intended for building other packages which
use the "gio-runtime" feature of the "%{crate}" crate.

%files       -n %{name}+gio-runtime-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+glib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+glib-devel %{_description}

This package contains library source intended for building other packages which
use the "glib" feature of the "%{crate}" crate.

%files       -n %{name}+glib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "openssl" feature of the "%{crate}" crate.

%files       -n %{name}+openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real-async-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real-async-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "real-async-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+real-async-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real-async-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real-async-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "real-async-tls" feature of the "%{crate}" crate.

%files       -n %{name}+real-async-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "real-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+real-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real-tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real-tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "real-tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+real-tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real-tokio-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real-tokio-openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "real-tokio-openssl" feature of the "%{crate}" crate.

%files       -n %{name}+real-tokio-openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+real-tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+real-tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "real-tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+real-tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-native-certs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-native-certs-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-native-certs" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-native-certs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-openssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-openssl-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-openssl" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-openssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-runtime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-runtime-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-runtime" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-runtime-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-rustls-native-certs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-native-certs-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-rustls-native-certs" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-rustls-native-certs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-rustls-webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-rustls-webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-rustls-webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+verbose-logging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+verbose-logging-devel %{_description}

This package contains library source intended for building other packages which
use the "verbose-logging" feature of the "%{crate}" crate.

%files       -n %{name}+verbose-logging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
