# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate core-foundation

Name:           rust-core-foundation
Version:        0.9.3
Release:        %autorelease
Summary:        Bindings to Core Foundation for macOS

# Upstream license specification: MIT / Apache-2.0
License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/core-foundation
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Bindings to Core Foundation for macOS.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mac_os_10_7_support-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mac_os_10_7_support-devel %{_description}

This package contains library source intended for building other packages which
use the "mac_os_10_7_support" feature of the "%{crate}" crate.

%files       -n %{name}+mac_os_10_7_support-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mac_os_10_8_features-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mac_os_10_8_features-devel %{_description}

This package contains library source intended for building other packages which
use the "mac_os_10_8_features" feature of the "%{crate}" crate.

%files       -n %{name}+mac_os_10_8_features-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "with-chrono" feature of the "%{crate}" crate.

%files       -n %{name}+with-chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "with-uuid" feature of the "%{crate}" crate.

%files       -n %{name}+with-uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
