# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate cosmic-text

Name:           rust-cosmic-text
Version:        0.10.0
Release:        %autorelease
Summary:        Pure Rust multi-line text handling

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/cosmic-text
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Pure Rust multi-line text handling.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%license %{crate_instdir}/fonts/FiraMono-LICENSE
%license %{crate_instdir}/fonts/NotoSans-LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fontconfig-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fontconfig-devel %{_description}

This package contains library source intended for building other packages which
use the "fontconfig" feature of the "%{crate}" crate.

%files       -n %{name}+fontconfig-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hashbrown-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hashbrown-devel %{_description}

This package contains library source intended for building other packages which
use the "hashbrown" feature of the "%{crate}" crate.

%files       -n %{name}+hashbrown-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+no_std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no_std-devel %{_description}

This package contains library source intended for building other packages which
use the "no_std" feature of the "%{crate}" crate.

%files       -n %{name}+no_std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+swash-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+swash-devel %{_description}

This package contains library source intended for building other packages which
use the "swash" feature of the "%{crate}" crate.

%files       -n %{name}+swash-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+syntect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+syntect-devel %{_description}

This package contains library source intended for building other packages which
use the "syntect" feature of the "%{crate}" crate.

%files       -n %{name}+syntect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sys-locale-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sys-locale-devel %{_description}

This package contains library source intended for building other packages which
use the "sys-locale" feature of the "%{crate}" crate.

%files       -n %{name}+sys-locale-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+vi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+vi-devel %{_description}

This package contains library source intended for building other packages which
use the "vi" feature of the "%{crate}" crate.

%files       -n %{name}+vi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+warn_on_missing_glyphs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+warn_on_missing_glyphs-devel %{_description}

This package contains library source intended for building other packages which
use the "warn_on_missing_glyphs" feature of the "%{crate}" crate.

%files       -n %{name}+warn_on_missing_glyphs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+wasm-web-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+wasm-web-devel %{_description}

This package contains library source intended for building other packages which
use the "wasm-web" feature of the "%{crate}" crate.

%files       -n %{name}+wasm-web-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
