# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate lipsum

Name:           rust-lipsum
Version:        0.8.0
Release:        %autorelease
Summary:        Lorem ipsum text generation library

License:        MIT
URL:            https://crates.io/crates/lipsum
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Lipsum is a lorem ipsum text generation library. Use this if you need
some filler text for your application. The text is generated using a
simple Markov chain, which you can also instantiate to generate your own
pieces of pseudo-random text.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
