# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate metal

Name:           rust-metal
Version:        0.21.0
Release:        %autorelease
Summary:        Rust bindings for Metal

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/metal
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Rust bindings for Metal.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dispatch-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dispatch-devel %{_description}

This package contains library source intended for building other packages which
use the "dispatch" feature of the "%{crate}" crate.

%files       -n %{name}+dispatch-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+dispatch-queue-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+dispatch-queue-devel %{_description}

This package contains library source intended for building other packages which
use the "dispatch-queue" feature of the "%{crate}" crate.

%files       -n %{name}+dispatch-queue-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mps-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mps-devel %{_description}

This package contains library source intended for building other packages which
use the "mps" feature of the "%{crate}" crate.

%files       -n %{name}+mps-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+private-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+private-devel %{_description}

This package contains library source intended for building other packages which
use the "private" feature of the "%{crate}" crate.

%files       -n %{name}+private-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
