# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate tonic

Name:           rust-tonic
Version:        0.6.0
Release:        %autorelease
Summary:        GRPC over HTTP/2 implementation focused on high performance, interoperability, and flexibility

License:        MIT
URL:            https://crates.io/crates/tonic
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A gRPC over HTTP/2 implementation focused on high performance,
interoperability, and flexibility.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
# FIXME: no license files detected
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-trait-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-trait-devel %{_description}

This package contains library source intended for building other packages which
use the "async-trait" feature of the "%{crate}" crate.

%files       -n %{name}+async-trait-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+codegen-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+codegen-devel %{_description}

This package contains library source intended for building other packages which
use the "codegen" feature of the "%{crate}" crate.

%files       -n %{name}+codegen-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+compression-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+compression-devel %{_description}

This package contains library source intended for building other packages which
use the "compression" feature of the "%{crate}" crate.

%files       -n %{name}+compression-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+flate2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+flate2-devel %{_description}

This package contains library source intended for building other packages which
use the "flate2" feature of the "%{crate}" crate.

%files       -n %{name}+flate2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+h2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+h2-devel %{_description}

This package contains library source intended for building other packages which
use the "h2" feature of the "%{crate}" crate.

%files       -n %{name}+h2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+hyper-timeout-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+hyper-timeout-devel %{_description}

This package contains library source intended for building other packages which
use the "hyper-timeout" feature of the "%{crate}" crate.

%files       -n %{name}+hyper-timeout-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prost-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prost-devel %{_description}

This package contains library source intended for building other packages which
use the "prost" feature of the "%{crate}" crate.

%files       -n %{name}+prost-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prost-derive-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prost-derive-devel %{_description}

This package contains library source intended for building other packages which
use the "prost-derive" feature of the "%{crate}" crate.

%files       -n %{name}+prost-derive-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+prost1-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+prost1-devel %{_description}

This package contains library source intended for building other packages which
use the "prost1" feature of the "%{crate}" crate.

%files       -n %{name}+prost1-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-native-certs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-native-certs-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-native-certs" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-native-certs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "tls-roots" feature of the "%{crate}" crate.

%files       -n %{name}+tls-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-roots-common-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-roots-common-devel %{_description}

This package contains library source intended for building other packages which
use the "tls-roots-common" feature of the "%{crate}" crate.

%files       -n %{name}+tls-roots-common-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "tls-webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+tls-webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tower-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tower-devel %{_description}

This package contains library source intended for building other packages which
use the "tower" feature of the "%{crate}" crate.

%files       -n %{name}+tower-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tracing-futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tracing-futures-devel %{_description}

This package contains library source intended for building other packages which
use the "tracing-futures" feature of the "%{crate}" crate.

%files       -n %{name}+tracing-futures-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+transport-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+transport-devel %{_description}

This package contains library source intended for building other packages which
use the "transport" feature of the "%{crate}" crate.

%files       -n %{name}+transport-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
