# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate sqlx

Name:           rust-sqlx
Version:        0.7.0
Release:        %autorelease
Summary:        🧰 The Rust SQL Toolkit

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/sqlx
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
🧰 The Rust SQL Toolkit. An async, pure Rust SQL crate featuring compile-
time checked queries without a DSL. Supports PostgreSQL, MySQL, and
SQLite.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/FAQ.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_rt-async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_rt-async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "_rt-async-std" feature of the "%{crate}" crate.

%files       -n %{name}+_rt-async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_rt-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_rt-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "_rt-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+_rt-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+_unstable-all-types-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+_unstable-all-types-devel %{_description}

This package contains library source intended for building other packages which
use the "_unstable-all-types" feature of the "%{crate}" crate.

%files       -n %{name}+_unstable-all-types-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+all-databases-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+all-databases-devel %{_description}

This package contains library source intended for building other packages which
use the "all-databases" feature of the "%{crate}" crate.

%files       -n %{name}+all-databases-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+any-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+any-devel %{_description}

This package contains library source intended for building other packages which
use the "any" feature of the "%{crate}" crate.

%files       -n %{name}+any-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bigdecimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bigdecimal-devel %{_description}

This package contains library source intended for building other packages which
use the "bigdecimal" feature of the "%{crate}" crate.

%files       -n %{name}+bigdecimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bit-vec-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bit-vec-devel %{_description}

This package contains library source intended for building other packages which
use the "bit-vec" feature of the "%{crate}" crate.

%files       -n %{name}+bit-vec-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ipnetwork-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ipnetwork-devel %{_description}

This package contains library source intended for building other packages which
use the "ipnetwork" feature of the "%{crate}" crate.

%files       -n %{name}+ipnetwork-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-devel %{_description}

This package contains library source intended for building other packages which
use the "json" feature of the "%{crate}" crate.

%files       -n %{name}+json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mac_address-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mac_address-devel %{_description}

This package contains library source intended for building other packages which
use the "mac_address" feature of the "%{crate}" crate.

%files       -n %{name}+mac_address-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macros-devel %{_description}

This package contains library source intended for building other packages which
use the "macros" feature of the "%{crate}" crate.

%files       -n %{name}+macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+migrate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+migrate-devel %{_description}

This package contains library source intended for building other packages which
use the "migrate" feature of the "%{crate}" crate.

%files       -n %{name}+migrate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mysql-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mysql-devel %{_description}

This package contains library source intended for building other packages which
use the "mysql" feature of the "%{crate}" crate.

%files       -n %{name}+mysql-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+postgres-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+postgres-devel %{_description}

This package contains library source intended for building other packages which
use the "postgres" feature of the "%{crate}" crate.

%files       -n %{name}+postgres-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+regexp-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+regexp-devel %{_description}

This package contains library source intended for building other packages which
use the "regexp" feature of the "%{crate}" crate.

%files       -n %{name}+regexp-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rust_decimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rust_decimal-devel %{_description}

This package contains library source intended for building other packages which
use the "rust_decimal" feature of the "%{crate}" crate.

%files       -n %{name}+rust_decimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlite-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlite" feature of the "%{crate}" crate.

%files       -n %{name}+sqlite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-macros-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-macros" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-mysql-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-mysql-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-mysql" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-mysql-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-postgres-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-postgres-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-postgres" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-postgres-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-sqlite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-sqlite-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-sqlite" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-sqlite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-none-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-none-devel %{_description}

This package contains library source intended for building other packages which
use the "tls-none" feature of the "%{crate}" crate.

%files       -n %{name}+tls-none-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tls-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tls-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "tls-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+tls-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
