# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate isahc

Name:           rust-isahc
Version:        1.7.2
Release:        %autorelease
Summary:        Practical HTTP client that is fun to use

License:        MIT
URL:            https://crates.io/crates/isahc
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
The practical HTTP client that is fun to use.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%license %{crate_instdir}/LICENSE-CC-BY
%license %{crate_instdir}/src/cookies/psl/list/LICENSE
%doc %{crate_instdir}/INTERNALS.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookies-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookies-devel %{_description}

This package contains library source intended for building other packages which
use the "cookies" feature of the "%{crate}" crate.

%files       -n %{name}+cookies-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+encoding_rs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+encoding_rs-devel %{_description}

This package contains library source intended for building other packages which
use the "encoding_rs" feature of the "%{crate}" crate.

%files       -n %{name}+encoding_rs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+http2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+http2-devel %{_description}

This package contains library source intended for building other packages which
use the "http2" feature of the "%{crate}" crate.

%files       -n %{name}+http2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+httpdate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+httpdate-devel %{_description}

This package contains library source intended for building other packages which
use the "httpdate" feature of the "%{crate}" crate.

%files       -n %{name}+httpdate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+json-devel %{_description}

This package contains library source intended for building other packages which
use the "json" feature of the "%{crate}" crate.

%files       -n %{name}+json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mime-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mime-devel %{_description}

This package contains library source intended for building other packages which
use the "mime" feature of the "%{crate}" crate.

%files       -n %{name}+mime-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nightly-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nightly-devel %{_description}

This package contains library source intended for building other packages which
use the "nightly" feature of the "%{crate}" crate.

%files       -n %{name}+nightly-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+parking_lot-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+parking_lot-devel %{_description}

This package contains library source intended for building other packages which
use the "parking_lot" feature of the "%{crate}" crate.

%files       -n %{name}+parking_lot-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+psl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+psl-devel %{_description}

This package contains library source intended for building other packages which
use the "psl" feature of the "%{crate}" crate.

%files       -n %{name}+psl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+publicsuffix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+publicsuffix-devel %{_description}

This package contains library source intended for building other packages which
use the "publicsuffix" feature of the "%{crate}" crate.

%files       -n %{name}+publicsuffix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+spnego-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spnego-devel %{_description}

This package contains library source intended for building other packages which
use the "spnego" feature of the "%{crate}" crate.

%files       -n %{name}+spnego-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+static-curl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+static-curl-devel %{_description}

This package contains library source intended for building other packages which
use the "static-curl" feature of the "%{crate}" crate.

%files       -n %{name}+static-curl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+static-ssl-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+static-ssl-devel %{_description}

This package contains library source intended for building other packages which
use the "static-ssl" feature of the "%{crate}" crate.

%files       -n %{name}+static-ssl-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+text-decoding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+text-decoding-devel %{_description}

This package contains library source intended for building other packages which
use the "text-decoding" feature of the "%{crate}" crate.

%files       -n %{name}+text-decoding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unstable-interceptors-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unstable-interceptors-devel %{_description}

This package contains library source intended for building other packages which
use the "unstable-interceptors" feature of the "%{crate}" crate.

%files       -n %{name}+unstable-interceptors-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
