# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate postage

Name:           rust-postage
Version:        0.5.0
Release:        %autorelease
Summary:        Async channel library

License:        MIT
URL:            https://crates.io/crates/postage
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An async channel library.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+blocking-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+blocking-devel %{_description}

This package contains library source intended for building other packages which
use the "blocking" feature of the "%{crate}" crate.

%files       -n %{name}+blocking-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-devel %{_description}

This package contains library source intended for building other packages which
use the "debug" feature of the "%{crate}" crate.

%files       -n %{name}+debug-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-devel %{_description}

This package contains library source intended for building other packages which
use the "futures" feature of the "%{crate}" crate.

%files       -n %{name}+futures-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-traits-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-traits-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-traits" feature of the "%{crate}" crate.

%files       -n %{name}+futures-traits-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+log-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+log-devel %{_description}

This package contains library source intended for building other packages which
use the "log" feature of the "%{crate}" crate.

%files       -n %{name}+log-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+logging-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+logging-devel %{_description}

This package contains library source intended for building other packages which
use the "logging" feature of the "%{crate}" crate.

%files       -n %{name}+logging-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+pollster-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+pollster-devel %{_description}

This package contains library source intended for building other packages which
use the "pollster" feature of the "%{crate}" crate.

%files       -n %{name}+pollster-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simple_logger-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simple_logger-devel %{_description}

This package contains library source intended for building other packages which
use the "simple_logger" feature of the "%{crate}" crate.

%files       -n %{name}+simple_logger-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
