# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate tiny-skia

Name:           rust-tiny-skia
Version:        0.5.0
Release:        %autorelease
Summary:        Tiny Skia subset ported to Rust

License:        BSD-3-Clause
URL:            https://crates.io/crates/tiny-skia
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A tiny Skia subset ported to Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+libm-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+libm-devel %{_description}

This package contains library source intended for building other packages which
use the "libm" feature of the "%{crate}" crate.

%files       -n %{name}+libm-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+png-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+png-devel %{_description}

This package contains library source intended for building other packages which
use the "png" feature of the "%{crate}" crate.

%files       -n %{name}+png-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+png-format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+png-format-devel %{_description}

This package contains library source intended for building other packages which
use the "png-format" feature of the "%{crate}" crate.

%files       -n %{name}+png-format-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+safe_arch-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+safe_arch-devel %{_description}

This package contains library source intended for building other packages which
use the "safe_arch" feature of the "%{crate}" crate.

%files       -n %{name}+safe_arch-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+simd-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+simd-devel %{_description}

This package contains library source intended for building other packages which
use the "simd" feature of the "%{crate}" crate.

%files       -n %{name}+simd-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+std-devel %{_description}

This package contains library source intended for building other packages which
use the "std" feature of the "%{crate}" crate.

%files       -n %{name}+std-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
