# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate tokio-tungstenite

Name:           rust-tokio-tungstenite
Version:        0.17.0
Release:        %autorelease
Summary:        Tokio binding for Tungstenite, the Lightweight stream-based WebSocket implementation

License:        MIT
URL:            https://crates.io/crates/tokio-tungstenite
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Tokio binding for Tungstenite, the Lightweight stream-based WebSocket
implementation.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+__rustls-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+__rustls-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "__rustls-tls" feature of the "%{crate}" crate.

%files       -n %{name}+__rustls-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+connect-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+connect-devel %{_description}

This package contains library source intended for building other packages which
use the "connect" feature of the "%{crate}" crate.

%files       -n %{name}+connect-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-crate-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-crate-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls-crate" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-crate-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+native-tls-vendored-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+native-tls-vendored-devel %{_description}

This package contains library source intended for building other packages which
use the "native-tls-vendored" feature of the "%{crate}" crate.

%files       -n %{name}+native-tls-vendored-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-native-certs-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-native-certs-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-native-certs" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-native-certs-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-tls-native-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-tls-native-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-tls-native-roots" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-tls-native-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustls-tls-webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustls-tls-webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "rustls-tls-webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+rustls-tls-webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+stream-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+stream-devel %{_description}

This package contains library source intended for building other packages which
use the "stream" feature of the "%{crate}" crate.

%files       -n %{name}+stream-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+webpki-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-devel %{_description}

This package contains library source intended for building other packages which
use the "webpki" feature of the "%{crate}" crate.

%files       -n %{name}+webpki-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+webpki-roots-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+webpki-roots-devel %{_description}

This package contains library source intended for building other packages which
use the "webpki-roots" feature of the "%{crate}" crate.

%files       -n %{name}+webpki-roots-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
