# Generated by rust2rpm 25
%bcond_without check

%global crate human_bytes

Name:           rust-human_bytes
Version:        0.4.1
Release:        %autorelease
Summary:        To convert bytes into human-readable values

License:        BSD-2-Clause
URL:            https://crates.io/crates/human_bytes
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Crate to convert bytes into human-readable values.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%license LICENSE.dependencies
%doc CHANGELOG.md
%doc README.md
%{_bindir}/hb

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+anyhow-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+anyhow-devel %{_description}

This package contains library source intended for building other packages which
use the "anyhow" feature of the "%{crate}" crate.

%files       -n %{name}+anyhow-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+atty-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+atty-devel %{_description}

This package contains library source intended for building other packages which
use the "atty" feature of the "%{crate}" crate.

%files       -n %{name}+atty-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+build-binary-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+build-binary-devel %{_description}

This package contains library source intended for building other packages which
use the "build-binary" feature of the "%{crate}" crate.

%files       -n %{name}+build-binary-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fast-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fast-devel %{_description}

This package contains library source intended for building other packages which
use the "fast" feature of the "%{crate}" crate.

%files       -n %{name}+fast-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+lexopt-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+lexopt-devel %{_description}

This package contains library source intended for building other packages which
use the "lexopt" feature of the "%{crate}" crate.

%files       -n %{name}+lexopt-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ryu-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ryu-devel %{_description}

This package contains library source intended for building other packages which
use the "ryu" feature of the "%{crate}" crate.

%files       -n %{name}+ryu-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+si-units-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+si-units-devel %{_description}

This package contains library source intended for building other packages which
use the "si-units" feature of the "%{crate}" crate.

%files       -n %{name}+si-units-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires -f build-binary

%build
%cargo_build -f build-binary
%{cargo_license_summary -f build-binary}
%{cargo_license -f build-binary} > LICENSE.dependencies

%install
%cargo_install -f build-binary

%if %{with check}
%check
%cargo_test -f build-binary
%endif

%changelog
%autochangelog
