# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate sea-orm

Name:           rust-sea-orm
Version:        0.12.0
Release:        %autorelease
Summary:        🐚 An async & dynamic ORM for Rust

License:        MIT OR Apache-2.0
URL:            https://crates.io/crates/sea-orm
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
🐚 An async & dynamic ORM for Rust.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/COMMUNITY.md
%doc %{crate_instdir}/CONTRIBUTING.md
%doc %{crate_instdir}/DESIGN.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+bigdecimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+bigdecimal-devel %{_description}

This package contains library source intended for building other packages which
use the "bigdecimal" feature of the "%{crate}" crate.

%files       -n %{name}+bigdecimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "chrono" feature of the "%{crate}" crate.

%files       -n %{name}+chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+debug-print-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+debug-print-devel %{_description}

This package contains library source intended for building other packages which
use the "debug-print" feature of the "%{crate}" crate.

%files       -n %{name}+debug-print-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+macros-devel %{_description}

This package contains library source intended for building other packages which
use the "macros" feature of the "%{crate}" crate.

%files       -n %{name}+macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+mock-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+mock-devel %{_description}

This package contains library source intended for building other packages which
use the "mock" feature of the "%{crate}" crate.

%files       -n %{name}+mock-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+postgres-array-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+postgres-array-devel %{_description}

This package contains library source intended for building other packages which
use the "postgres-array" feature of the "%{crate}" crate.

%files       -n %{name}+postgres-array-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-actix-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-actix-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-actix" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-actix-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-actix-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-actix-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-actix-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-actix-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-actix-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-actix-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-actix-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-actix-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-async-std-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-async-std-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-async-std-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-async-std-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-native-tls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-native-tls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio-native-tls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-native-tls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+runtime-tokio-rustls-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+runtime-tokio-rustls-devel %{_description}

This package contains library source intended for building other packages which
use the "runtime-tokio-rustls" feature of the "%{crate}" crate.

%files       -n %{name}+runtime-tokio-rustls-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rust_decimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rust_decimal-devel %{_description}

This package contains library source intended for building other packages which
use the "rust_decimal" feature of the "%{crate}" crate.

%files       -n %{name}+rust_decimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sea-orm-internal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sea-orm-internal-devel %{_description}

This package contains library source intended for building other packages which
use the "sea-orm-internal" feature of the "%{crate}" crate.

%files       -n %{name}+sea-orm-internal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sea-query-binder-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sea-query-binder-devel %{_description}

This package contains library source intended for building other packages which
use the "sea-query-binder" feature of the "%{crate}" crate.

%files       -n %{name}+sea-query-binder-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-all-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-all-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-all" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-all-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-dep-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-dep-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-dep" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-dep-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-mysql-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-mysql-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-mysql" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-mysql-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-postgres-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-postgres-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-postgres" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-postgres-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+sqlx-sqlite-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+sqlx-sqlite-devel %{_description}

This package contains library source intended for building other packages which
use the "sqlx-sqlite" feature of the "%{crate}" crate.

%files       -n %{name}+sqlx-sqlite-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+tests-cfg-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+tests-cfg-devel %{_description}

This package contains library source intended for building other packages which
use the "tests-cfg" feature of the "%{crate}" crate.

%files       -n %{name}+tests-cfg-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+time-devel %{_description}

This package contains library source intended for building other packages which
use the "time" feature of the "%{crate}" crate.

%files       -n %{name}+time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "uuid" feature of the "%{crate}" crate.

%files       -n %{name}+uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-bigdecimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-bigdecimal-devel %{_description}

This package contains library source intended for building other packages which
use the "with-bigdecimal" feature of the "%{crate}" crate.

%files       -n %{name}+with-bigdecimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-chrono-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-chrono-devel %{_description}

This package contains library source intended for building other packages which
use the "with-chrono" feature of the "%{crate}" crate.

%files       -n %{name}+with-chrono-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-json-devel %{_description}

This package contains library source intended for building other packages which
use the "with-json" feature of the "%{crate}" crate.

%files       -n %{name}+with-json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-rust_decimal-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-rust_decimal-devel %{_description}

This package contains library source intended for building other packages which
use the "with-rust_decimal" feature of the "%{crate}" crate.

%files       -n %{name}+with-rust_decimal-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-time-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-time-devel %{_description}

This package contains library source intended for building other packages which
use the "with-time" feature of the "%{crate}" crate.

%files       -n %{name}+with-time-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+with-uuid-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+with-uuid-devel %{_description}

This package contains library source intended for building other packages which
use the "with-uuid" feature of the "%{crate}" crate.

%files       -n %{name}+with-uuid-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
