# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate flume

Name:           rust-flume
Version:        0.11.0
Release:        %autorelease
Summary:        Blazingly fast multi-producer channel

# Upstream license specification: Apache-2.0/MIT
License:        Apache-2.0 OR MIT
URL:            https://crates.io/crates/flume
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
A blazingly fast multi-producer channel.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE-APACHE
%license %{crate_instdir}/LICENSE-MIT
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+async-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+async-devel %{_description}

This package contains library source intended for building other packages which
use the "async" feature of the "%{crate}" crate.

%files       -n %{name}+async-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+eventual-fairness-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+eventual-fairness-devel %{_description}

This package contains library source intended for building other packages which
use the "eventual-fairness" feature of the "%{crate}" crate.

%files       -n %{name}+eventual-fairness-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-core-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-core-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-core" feature of the "%{crate}" crate.

%files       -n %{name}+futures-core-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+futures-sink-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+futures-sink-devel %{_description}

This package contains library source intended for building other packages which
use the "futures-sink" feature of the "%{crate}" crate.

%files       -n %{name}+futures-sink-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+nanorand-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+nanorand-devel %{_description}

This package contains library source intended for building other packages which
use the "nanorand" feature of the "%{crate}" crate.

%files       -n %{name}+nanorand-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+select-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+select-devel %{_description}

This package contains library source intended for building other packages which
use the "select" feature of the "%{crate}" crate.

%files       -n %{name}+select-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+spin-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spin-devel %{_description}

This package contains library source intended for building other packages which
use the "spin" feature of the "%{crate}" crate.

%files       -n %{name}+spin-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
