# Generated by rust2rpm 25
%bcond_without check
%global debug_package %{nil}

%global crate axum-extra

Name:           rust-axum-extra
Version:        0.3.0
Release:        %autorelease
Summary:        Extra utilities for axum

License:        MIT
URL:            https://crates.io/crates/axum-extra
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Extra utilities for axum.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+axum-macros-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+axum-macros-devel %{_description}

This package contains library source intended for building other packages which
use the "axum-macros" feature of the "%{crate}" crate.

%files       -n %{name}+axum-macros-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-lib-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-lib-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie-lib" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-lib-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-private-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-private-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie-private" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-private-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cookie-signed-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cookie-signed-devel %{_description}

This package contains library source intended for building other packages which
use the "cookie-signed" feature of the "%{crate}" crate.

%files       -n %{name}+cookie-signed-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+erased-json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+erased-json-devel %{_description}

This package contains library source intended for building other packages which
use the "erased-json" feature of the "%{crate}" crate.

%files       -n %{name}+erased-json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+percent-encoding-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+percent-encoding-devel %{_description}

This package contains library source intended for building other packages which
use the "percent-encoding" feature of the "%{crate}" crate.

%files       -n %{name}+percent-encoding-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde-devel %{_description}

This package contains library source intended for building other packages which
use the "serde" feature of the "%{crate}" crate.

%files       -n %{name}+serde-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+serde_json-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+serde_json-devel %{_description}

This package contains library source intended for building other packages which
use the "serde_json" feature of the "%{crate}" crate.

%files       -n %{name}+serde_json-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+spa-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+spa-devel %{_description}

This package contains library source intended for building other packages which
use the "spa" feature of the "%{crate}" crate.

%files       -n %{name}+spa-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+typed-routing-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+typed-routing-devel %{_description}

This package contains library source intended for building other packages which
use the "typed-routing" feature of the "%{crate}" crate.

%files       -n %{name}+typed-routing-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
