# Generated by rust2rpm 25
%bcond_without check

%global crate usvg

Name:           rust-usvg
Version:        0.14.0
Release:        %autorelease
Summary:        SVG simplification library

License:        MPL-2.0
URL:            https://crates.io/crates/usvg
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
An SVG simplification library.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
# FIXME: paste output of %%cargo_license_summary here
License:        # FIXME
# LICENSE.dependencies contains a full license breakdown

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE.txt
%license LICENSE.dependencies
%doc README.md
%{_bindir}/usvg

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE.txt
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+fontdb-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+fontdb-devel %{_description}

This package contains library source intended for building other packages which
use the "fontdb" feature of the "%{crate}" crate.

%files       -n %{name}+fontdb-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+memmap2-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+memmap2-devel %{_description}

This package contains library source intended for building other packages which
use the "memmap2" feature of the "%{crate}" crate.

%files       -n %{name}+memmap2-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+rustybuzz-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+rustybuzz-devel %{_description}

This package contains library source intended for building other packages which
use the "rustybuzz" feature of the "%{crate}" crate.

%files       -n %{name}+rustybuzz-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+system-fonts-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+system-fonts-devel %{_description}

This package contains library source intended for building other packages which
use the "system-fonts" feature of the "%{crate}" crate.

%files       -n %{name}+system-fonts-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+text-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+text-devel %{_description}

This package contains library source intended for building other packages which
use the "text" feature of the "%{crate}" crate.

%files       -n %{name}+text-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+ttf-parser-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+ttf-parser-devel %{_description}

This package contains library source intended for building other packages which
use the "ttf-parser" feature of the "%{crate}" crate.

%files       -n %{name}+ttf-parser-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicode-bidi-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicode-bidi-devel %{_description}

This package contains library source intended for building other packages which
use the "unicode-bidi" feature of the "%{crate}" crate.

%files       -n %{name}+unicode-bidi-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicode-script-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicode-script-devel %{_description}

This package contains library source intended for building other packages which
use the "unicode-script" feature of the "%{crate}" crate.

%files       -n %{name}+unicode-script-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+unicode-vo-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+unicode-vo-devel %{_description}

This package contains library source intended for building other packages which
use the "unicode-vo" feature of the "%{crate}" crate.

%files       -n %{name}+unicode-vo-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} > LICENSE.dependencies

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
